apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jo3lcfzud-nodejs
  janus-idp.io/tekton: jo3lcfzud-nodejs
  backstage.io/kubernetes-id: jo3lcfzud-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jo3lcfzud-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
